# Example for parameters to excecute

# I/O
io_parameters:
  data_tiled_uri: http://localhost:8000/api/v1/metadata/
  data_tiled_api_key: secret
  mask_tiled_uri: http://localhost:8000/api/v1/metadata/built-masks
  mask_tiled_api_key: secret
  seg_tiled_uri: http://localhost:8000/api/v1/metadata/outlive/saved-segments
  seg_tiled_api_key: secret
  uid_save: http://localhost:8000/api/v1/metadata/outlive/model-metric
  uid_retrieve: http://localhost:8000/api/v1/metadata/outlive/model-metric
  models_dir: http://localhost:8000/api/v1/metadata/outlive/results

model_parameters:
  network: "MSDNet"
  num_classes: 3
  num_epochs: 3
  optimizer: "Adam"
  criterion: "CrossEntropyLoss"
  weights: "[1.0, 2.0, 0.5]"
  learning_rate: 0.1
  activation: "ReLU"
  normalization: "BatchNorm2d"
  convolution: "Conv2d"

  qlty_window: 50
  qlty_step: 30
  qlty_border: 3

  shuffle_train: True
  batch_size_train: 1

  batch_size_val: 1

  batch_size_inference: 1
  val_pct: 0.2

  layer_width: 1
  num_layers: 3
  custom_dilation: True
  dilation_array: "[1, 2, 4]"